### ISSUE TITLE
Solving invertible matrix systems is sometimes producing NaN arrays, probably due to pivoting

### ISSUE THREAD

**Issue by canmom** [ryry0/elm-numeric#2]
When using the `solveV` function to solve a matrix system, sometimes instead of a solution matrix or an `Err`, I receive a matrix where all values are the floating-point value `NaN`. This problem also appears to affect `luDecomp`, `det`, and `invert` and probably other functions.

An example of a simple matrix with this problem:
``` Elm
import Matrix

m = Matrix.from2DList
    [ [ 0, 0,-1, 1]
    , [ 0,-1, 1, 0]
    , [-1, 1, 0, 0]
    , [ 1, 0, 0, 0]
    ]

rhs = Matrix.cvecFromList [0, 0, 1, 1]

lu = Matrix.luDecomp m
-- (Mat { dimensions = (4,4), elements = Array.fromList [1,0,0,0,NaN,NaN,NaN,NaN,-Infinity,NaN,NaN,NaN,Infinity,NaN,NaN,NaN] },Mat { dimensions = (4,4), elements = Array.fromList [0,0,-1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN] })

det = Matrix.det m
-- Just NaN

soln = Matrix.solveV m rhs
-- Mat { dimensions = (4,1), elements = Array.fromList [NaN,NaN,NaN,NaN] }

mInv = Matrix.invert m -- produces NaN matrix
-- Mat { dimensions = (4,4), elements = Array.fromList [NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN] }
```
For comparison, the same matrix can be inverted in numpy:
``` Python
import numpy as np
import scipy.linalg

m = np.array([[0,0,-1,1],
    [0,-1,1,0],
    [-1,1,0,0],
    [1,0,0,0]])

rhs = np.array([[0],[0],[1],[1]])

det = np.linalg.det(

soln = np.linalg.solve(m,rhs)
# array([[1.],
#       [2.],
#       [2.],
#       [2.]])

mInv = np.linalg.inv(m)
# array([[0., 0., 0., 1.],
#       [0., 0., 1., 1.],
#       [0., 1., 1., 1.],
#       [1., 1., 1., 1.]])

lu = scipy.linalg.lu(m)
# PLU decomposition:
# pivot: array([[0., 0., 1., 0.],
#       [0., 1., 0., 0.],
#       [1., 0., 0., 0.],
#       [0., 0., 0., 1.]]),
# L:  array([[ 1.,  0.,  0.,  0.],
#       [-0.,  1.,  0.,  0.],
#       [-0., -0.,  1.,  0.],
#       [-1., -1., -1.,  1.]]),
# U: array([[-1.,  1.,  0.,  0.],
#       [ 0., -1.,  1.,  0.],
#       [ 0.,  0., -1.,  1.],
#       [ 0.,  0.,  0.,  1.]]))
```

I believe that this is because this matrix requires pivoting when it's (P)LU decomposed, and all of these functions depend on `luNoPivotSingle` which doesn't support pivoting.

Please would it be possible to add support pivoting to the underlying LU algorithm? If that is not practical, would it be possible to amend the documentation to warn about this potential issue in `solveV` and similar functions?

**Comment by ryry0** [comment]
Thank you for opening an issue! I really appreciate you using my library. 

Pivoting is something I've been wanting to implement for a long time. I'm on a break from school now so I may have some time to work on this. How about I'll put some time into this, and if I'm unable to finish by the time my break is over, I'll amend the documentation.

Does that sound good?
Have you found any other bugs or do you have any other feature requests/usability issues? Please let me know!!

**Comment by canmom** [comment]
Hi, thanks so much for writing it, and for looking into this! So far this is the only major issue I've had, it's a very handy library.

For some context on where this came up - I'm working for [an online education company](https://brilliant.org) where I'm writing a DC circuit simulator, which involves [converting a circuit diagram into a matrix equation](https://lpsa.swarthmore.edu/Systems/Electrical/mna/MNA2.html), then solving it to get voltages and currents. The problem comes up when I have a node of the circuit with no resistors connecting to it, which leads to a zero on the diagonal of the matrix.

My supervisor asked me to have a look into whether I can implement pivoting myself and hopefully submit a PR, so I'll let you know if I make any progress on this end!

**Comment by canmom** [comment]
Hi, an update - I've made some progress towards reimplementing LU factorisation and teaching myself how Crout's method works. So far [this WIP refactor](https://github.com/canmom/elm-numeric/commit/f45ce0c9f7c3581874ee977385474d0c80836102) runs LU factorisation about 300% faster than before on a small matrix without any pivoting - I'm sure this could run faster, there's some ugly array/list swapping in there. I've also optimised a couple of other functions like `getRows` and `getColumns`.

*Theoretically*, this also has code for pivot-selection/row-swapping in there (at the cost of about a quarter of the speed), but I've made a mistake somewhere in the algorithm so it's not giving correct results yet! I also want to experiment with some variants like searching for the pivot at the same time as computing the elements of the L matrix, like in the C version, in case this turns out to be faster.

**Comment by ryry0** [comment]
Thank you for this update! And for going above and beyond by optimizing those helper functions! 

Several things have come up during my break and I had to travel, and I will need to travel over the next couple of days, therefore I haven't been able to do much on my end. So I really appreciate your work on this. Once I'm done travelling I can take a look at your work more and help debug it.

Thanks again!

**Comment by ryry0** [comment]
Hey  @canmom, how is it coming along? I've got around to looking at your fork (specifically your last working commit `95ca0d6eb`), and it seems like you've done some great work since your `f45ce0c9f` commit. I played around with it and the LU function is looking good. 

Is there anything I can do to help you? I wrote some small functions to recreate the L and U matrices from the `LUElements` type as well as a function to unpermute a matrix given the `LUElements` permutation list. You probably have those already, though! 

I'd also love to hear your ideas behind how you went about optimizing the other parts of the code! I know tail-call recursion is faster since you don't grow a stack, and arrays are faster because O(1) indexing, but since it's transpiled to JS I'm not really familiar with the nuances of JS memory management and bottlenecks. 

As far as I understand your implementation right now, reversing the return values allows instant appending vs needing to traverse the list to append to the end? Is there no "tail pointer" under the hood? It looks like this decision also helps tail-call recursion? Please let me know if I'm mistaken.

Thanks again for your work!

**Comment by canmom** [comment]
Hi @ryry0, sorry for the delay getting back to you! I had to take a break from working on `elm-numeric` because something else came up, but I should hopefully be able to finish my implementation soon.

I had a look at the implementations under the hood in the Elm core libraries, which were instructive with helping work out what's performant.

In general, 'Arrays' (which are really trees with 32 branches per level! Elm doesn't have anything with constant-time access, I guess down to mutability) seem to be very slow for anything involving iteration compared to linked lists - if you're randomly accessing only a few items they're much faster, but once you want to iterate over an array, tail recursion just seems to win every time. It does look like working with arrays fast seems to largely rely on using the core library's wrappers over native Javascript functions, while by comparison the [`List` library](https://github.com/elm/core/blob/1.0.5/src/List.elm) is mostly pure Elm, and also largely based on tail recursion.

As far as I can tell, Elm lists are just singly linked lists under the hood. (Although in practice they may be stored as Javascript arrays, to avoid stack issues? But Elm tries very hard to make them accessible as singly linked lists!) The Elm optimising compiler really doesn't seem to do very much at the moment (I get similar performance with and without the `--optimize` flag, assuming I remove debug statements) but maybe in the future it will save us some more trouble.

With regard to reversing - that's exactly right, it's cheap to prepend to a list but expensive to append. I tried to avoid traversing a list as much as possible, so if I knew I'd be iterating twice over a list, it would generally be faster to hold it in reverse in the intermediate step. It definitely adds some conceptual overhead, but hopefully the speedup will be worth it!

My process is mostly to try a refactor, test it against the current version using `elm-benchmark` and some test data, and check for correctness by working through the algorithm by hand and feeding in intermediate steps. This means the versions that I'm testing should be as JIT-optimised as possible.

I'm going to be working on wiring up the last interchange step today, I'll let you know how it goes!

**Comment by ryry0** [comment]
Hey @canmom, thanks for continuing to work on this! No worries about the delay, as you can see I've been quite busy myself. I'm about to finish my graduate program so I've had a bunch of things I've needed to take care of and tie up. I'll be free for elm ventures in a month or so :)

I appreciate that writeup on what goes on under the hood! I'm incredibly surprised that 'Arrays' are 'Trees'! I can see how they can be very slow. I'm glad that I ended up implementing matrix multiplication and others in `List` form. Do you think it's worth moving the base datatype to a `List` instead of an `Array`? It's very cool to hear that the `List` implementation is almost pure Elm. 

If I remember right, the `--optimize` flag mainly did 'tree-shaking' or some term like that, removing all javascript that doesn't actually have to be transpiled, e.g. if a function is never called. That may be why you don't see much of a difference performance-wise!

That sounds like a great way of working through it! I appreciate your focus on making sure it's all optimized :) Keep me updated with any further developments on your end, and let me know if you'd need any help! I can take up the slack once I've graduated.

**Comment by kraklin** [comment]
Hey guys, I'm having similar problem where I'm getting `NaN` for `solve` and `det` functions for no obvious reason:

```elm
> Matrix.fromList (2,2) [0,1,1,0] |> Matrix.det
Just NaN : Maybe Float
```

This should be `-1`, right? Is it this bug or am I doing something wrong?
